### ISSUE TITLE
Float64 precision not preserved in Pytorch

### ISSUE THREAD

**Issue by playertr** [decargroup/pymlg#21]
I noticed that sometimes, floating-point precision is not preserved:

```
from pymlg.torch import SE3
import torch

T = torch.eye(4, dtype=torch.float64).unsqueeze(0)
print(SE3.from_components(*SE3.to_components(T)).dtype)
```

It looks like this is due to `batch_eye` generating a Float32 Tensor within `from_components` rather than matching the input dtype. This has downstream impacts on `SE3.inverse` and `SE3.random`.

Is this repo actively maintained? It looks like preserving the `dtype` and `device` fields of tensors in these torch operations could be a big benefit. I'm not sure of my own availability to submit the PR for it but I'm interested.

**Comment by CharlesCossette** [comment]
Hey there! Looks like this was fix here:
https://github.com/decargroup/pymlg/pull/22
